### ISSUE TITLE
Add a Zig sample

### ISSUE THREAD

**Issue by sdeleuze** [vmware-labs/wasm-languages#8]
See https://ziglang.org/.

**Comment by linux-china** [comment]
I built a  Zig Wasm/Wasi demo and  run with [Node](https://nodejs.org/)/[Deno](https://deno.land/)/[Bun](https://bun.sh/) and [wasmtime](https://github.com/bytecodealliance/wasmtime).  

repo:   https://github.com/linux-china/zig-wasm-demo

**Comment by sdeleuze** [comment]
Nice, thanks for sharing I will have a deeper look.
